org.gradle.caching=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.configureondemand=true
org.gradle.daemon=false
org.gradle.workers.max=4
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
